# Site settings
title: State of the Map Madagasikara 2024
email: sotm.mg@gmail.com
description: "State of the Map Madagasikara est la première rencontre nationale OpenstreetMap . Cet évènement vise à regrouper pendant 2 jours, les 29 et 30 avril les contributrices et contributeurs, utilisateurs, représentants de collectivités, d'entreprises, chercheurs mais aussi toute personne curieuse de découvrir cette « carte libre du monde » que représente OpenStreetMap."
url: "https://sotm2024.openstreetmap.mg/" # the base hostname & protocol for your site
twitter_username: state
github_username:  jekyll

# Build settings
markdown: kramdown

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#ffd97e' # yellow
  primary-light: '#e23e36' # red
  background-light: '#ffd97e'
  links: '#e23e36'
  links-light: '#b7d7e1'
  links-white: '#fff'
  text: '#030304'
  text-light: '#fff'

# Settings for map tiles used in leaflet maps
map_tiles:
  url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
  attribution: '&copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors'
  maxZoom: 19

# Repo files to not include in built site
exclude:
  - Dockerfile*
  - docker-compose.*
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

permalink: /:title/
relative_permalinks: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:title/

plugins:
  - jekyll-gzip
  # - jekyll-brotli
